function [ smoothed_ND_sensors ] = smoothStartEndNDSensors( ND_sensors, ...
                                                            percentage_padding, ...
                                                            percentage_smoothing_points, ...
                                                            mode, dt, ...
                                                            varargin )
    if (nargin > 5)
        fc  = varargin{1};
    else
        fc  = 40;                   % 40 Hz cutoff frequency
    end
    
    fs      = 1/dt;                 % sampling frequency
    [b, a]  = butter(2, fc/(fs/2)); % 2nd order Butterworth filter
    
    smoothed_ND_sensors     = smoothStartEndNDPositionProfile( ND_sensors, ...
                                                               percentage_padding, ...
                                                               percentage_smoothing_points, ...
                                                               mode, b, a );
end

