function [ smoothed_ND_position_prof ] = smoothStartEndNDPositionProfile( ND_position_prof, ...
                                                                          percentage_padding, ...
                                                                          percentage_smoothing_points, ...
                                                                          mode, ...
                                                                          b, a )
    smoothed_ND_position_prof           = zeros(size(ND_position_prof));
    D   = size(ND_position_prof,2);
    for d=1:D
        smoothed_ND_position_prof(:,d)  = smoothStartEnd1DPositionProfile( ND_position_prof(:,d), ...
                                                                           percentage_padding, ...
                                                                           percentage_smoothing_points, ...
                                                                           mode, ...
                                                                           b, a );
    end
end