function [ loa_feat_param ] = initializeAllInvolvedLOAparams( varargin )
    loa_feat_methods                = varargin{1};
    c_order                         = varargin{2};
    learning_param                  = varargin{3};
    unrolling_param                 = varargin{4};
    feat_constraint_mode            = varargin{5};
    if (nargin > 5)
        is_tau_invariant            = varargin{6};
    else
        is_tau_invariant            = 1;    % default is tau-invariant
    end
    
    N_AF_H14_beta_phi1_phi2_grid 	= 10;
    AF_H14_beta_phi1_phi2_low       = 1.0/pi;
    AF_H14_beta_phi1_phi2_high      = 21.0/pi;
    N_AF_H14_k_phi1_phi2_grid       = 10;
    AF_H14_k_phi1_phi2_low          = 0.05;
    AF_H14_k_phi1_phi2_high         = 0.75;
    N_AF_H14_k_phi3_grid            = 10;
    AF_H14_k_phi3_low               = 0.05;
    AF_H14_k_phi3_high              = 0.75;

    N_PF_DYN2_beta_grid             = 5;
    PF_DYN2_beta_low                = 0.5;
    PF_DYN2_beta_high               = 2.5;
    N_PF_DYN2_k_grid                = 5;
    PF_DYN2_k_low                   = 0.01;
    PF_DYN2_k_high                  = 0.5;

    if (unrolling_param.is_comparing_with_cpp_implementation)
        % C++ Implementation Comparison Test Parameters:
        N_GS_KGFv01_beta_grid       = 5;
        GS_KGFv01_beta_low          = 0;
        GS_KGFv01_beta_high         = pi;
        N_GS_KGFv01_k_grid          = 5;
        GS_KGFv01_k_low             = 0.01;
        GS_KGFv01_k_high            = 0.5;
        N_GS_KGFv01_s_grid          = 5;
    else
        N_GS_KGFv01_beta_grid       = 5;
        GS_KGFv01_beta_low          = 0;
        GS_KGFv01_beta_high         = pi;
        N_GS_KGFv01_k_grid          = 5;
        GS_KGFv01_k_low             = 0.01;
        GS_KGFv01_k_high            = 0.5;
        N_GS_KGFv01_s_grid          = 5;
    end

    N_FM_KGFv01_k_grid              = 3;
    FM_KGFv01_k_low                 = 0.01;
    FM_KGFv01_k_high                = 0.5;
    N_FM_KGFv01_s_grid              = 10;

    N_PF_DYN3_beta_grid             = 5;
    PF_DYN3_beta_low                = 0.0;
    PF_DYN3_beta_high               = 1.0;
    N_PF_DYN3_k_grid                = 5;
    PF_DYN3_k_low                   = 0.01;
    PF_DYN3_k_high                  = 0.5;
%     N_PF_DYN3_s_grid                = 5;
    N_PF_DYN3_s_grid                = 7;

    N_UC_AF_H14_beta_phi1_phi2_grid = 10;
    UC_AF_H14_beta_phi1_phi2_low    = 1.0/pi;
    UC_AF_H14_beta_phi1_phi2_high   = 21.0/pi;
    N_UC_AF_H14_k_phi1_phi2_grid   	= 10;
    UC_AF_H14_k_phi1_phi2_low      	= 0.05;
    UC_AF_H14_k_phi1_phi2_high   	= 0.75;
    N_UC_AF_H14_k_phi3_grid       	= 10;
    UC_AF_H14_k_phi3_low          	= 0.05;
    UC_AF_H14_k_phi3_high        	= 0.75;
    
    N_PF_DYN4_k_grid                = 5;
    PF_DYN4_k_low                   = 0.01;
    PF_DYN4_k_high                  = 0.5;
    N_PF_DYN4_s_grid                = 5;
    
    NN_net_struct                   = [20 10];  %[10 5]; %
    NN_N_feats                      = 17;

    point_feat_mode     = '_SUM_OBS_POINTS_FEATURE_CONTRIBUTION_';

    loa_feat_param   	= initializeLearnObsAvoidFeatParam(c_order, learning_param.learning_constraint_mode, is_tau_invariant);
    if (isMemberLOAFeatMethods(0, loa_feat_methods))
        [ loa_feat_param ] = initializeAF_H14LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                     N_AF_H14_beta_phi1_phi2_grid, ...
                                                                     AF_H14_beta_phi1_phi2_low, ...
                                                                     AF_H14_beta_phi1_phi2_high, ...
                                                                     N_AF_H14_k_phi1_phi2_grid, ...
                                                                     AF_H14_k_phi1_phi2_low, ...
                                                                     AF_H14_k_phi1_phi2_high, ...
                                                                     N_AF_H14_k_phi3_grid, ...
                                                                     AF_H14_k_phi3_low, ...
                                                                     AF_H14_k_phi3_high, ...
                                                                     '_INVERSE_QUADRATIC_', ...
                                                                     point_feat_mode, ...
                                                                     feat_constraint_mode );
    end

    if (isMemberLOAFeatMethods(1, loa_feat_methods))
        [ loa_feat_param ] = initializePF_DYN2LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                      N_PF_DYN2_beta_grid, ...
                                                                      PF_DYN2_beta_low, ...
                                                                      PF_DYN2_beta_high, ...
                                                                      N_PF_DYN2_k_grid, ...
                                                                      PF_DYN2_k_low, ...
                                                                      PF_DYN2_k_high, ...
                                                                      '_INVERSE_QUADRATIC_', ...
                                                                      point_feat_mode, ...
                                                                      feat_constraint_mode );
    end

    if (isMemberLOAFeatMethods(2, loa_feat_methods))
        [ loa_feat_param ] = initializeGS_KGFv01LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                        N_GS_KGFv01_beta_grid, ...
                                                                        GS_KGFv01_beta_low, ...
                                                                        GS_KGFv01_beta_high, ...
                                                                        N_GS_KGFv01_k_grid, ...
                                                                        GS_KGFv01_k_low, ...
                                                                        GS_KGFv01_k_high, ...
                                                                        N_GS_KGFv01_s_grid, ...
                                                                        c_order, ...
                                                                        feat_constraint_mode );
    end

    if (isMemberLOAFeatMethods(3, loa_feat_methods))
        [ loa_feat_param ] = initializeFM_KGFv01LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                        N_FM_KGFv01_k_grid, ...
                                                                        FM_KGFv01_k_low, ...
                                                                        FM_KGFv01_k_high, ...
                                                                        N_FM_KGFv01_s_grid, ...
                                                                        c_order );
    end

    if (isMemberLOAFeatMethods(4, loa_feat_methods))
        [ loa_feat_param ] = initializePF_DYN3LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                      N_PF_DYN3_beta_grid, ...
                                                                      PF_DYN3_beta_low, ...
                                                                      PF_DYN3_beta_high, ...
                                                                      N_PF_DYN3_k_grid, ...
                                                                      PF_DYN3_k_low, ...
                                                                      PF_DYN3_k_high, ...
                                                                      N_PF_DYN3_s_grid, ...
                                                                      c_order, ...
                                                                      feat_constraint_mode );
    end
    
    if (isMemberLOAFeatMethods(5, loa_feat_methods))
        feat_constraint_mode    = '_UNCONSTRAINED_'; % this is the unconstrained version of Akshara's features
        [ loa_feat_param ] = initializeAF_H14LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                     N_UC_AF_H14_beta_phi1_phi2_grid, ...
                                                                     UC_AF_H14_beta_phi1_phi2_low, ...
                                                                     UC_AF_H14_beta_phi1_phi2_high, ...
                                                                     N_UC_AF_H14_k_phi1_phi2_grid, ...
                                                                     UC_AF_H14_k_phi1_phi2_low, ...
                                                                     UC_AF_H14_k_phi1_phi2_high, ...
                                                                     N_UC_AF_H14_k_phi3_grid, ...
                                                                     UC_AF_H14_k_phi3_low, ...
                                                                     UC_AF_H14_k_phi3_high, ...
                                                                     '_INVERSE_QUADRATIC_', ...
                                                                     point_feat_mode, ...
                                                                     feat_constraint_mode );
    end

    if (isMemberLOAFeatMethods(6, loa_feat_methods))
        [ loa_feat_param ] = initializePF_DYN4LearnObsAvoidFeatParam( loa_feat_param, ...
                                                                      N_PF_DYN4_k_grid, ...
                                                                      PF_DYN4_k_low, ...
                                                                      PF_DYN4_k_high, ...
                                                                      N_PF_DYN4_s_grid, ...
                                                                      c_order, ...
                                                                      feat_constraint_mode );
    end

    if (isMemberLOAFeatMethods(7, loa_feat_methods))
        [ loa_feat_param ] = initializeNNLearnObsAvoidFeatParam( loa_feat_param, ...
                                                                 NN_net_struct, ...
                                                                 NN_N_feats );
    end
end

