function [ varargout ] = computeQuatDMPCtTarget( Quat_demo_coupled_traj,...
                                                 Quat_dmp_baseline_params )
    ID      = 1;
    
    dcp_quaternion('init', ID, Quat_dmp_baseline_params.n_rfs, num2str(ID), Quat_dmp_baseline_params.c_order);
    dcp_quaternion('reset_state', ID, Quat_dmp_baseline_params.fit_mean_Q0);
    dcp_quaternion('set_goal', ID, Quat_dmp_baseline_params.fit_mean_QG, 1);
    
%     [Quat_dmp_Ct_target, ...
%      Quat_dmp_Ct_target_cell, ...
%      Quat_dmp_Ft]   = dcp_quaternion('batch_compute_target_ct', ID, ...
%                                      Quat_dmp_baseline_params.dt, ...
%                                      Quat_dmp_baseline_params.w, ...
%                                      Quat_demo_coupled_traj, ...
%                                      Quat_dmp_baseline_params.fit_mean_Q0, ...
%                                      Quat_dmp_baseline_params.fit_mean_QG);
    [Quat_dmp_Ct_target, ...
     Quat_dmp_Ct_target_cell, ...
     Quat_dmp_Ft]   = dcp_quaternion('batch_compute_target_ct', ID, ...
                                     Quat_dmp_baseline_params.dt, ...
                                     Quat_dmp_baseline_params.w, ...
                                     Quat_demo_coupled_traj, ...
                                     Quat_demo_coupled_traj{1,1}(:,1), ...
                                     Quat_dmp_baseline_params.fit_mean_QG, ...
                                     1);
    
    varargout(1)    = {Quat_dmp_Ct_target};
    if (nargout > 1)
        varargout(2)= {Quat_dmp_Ct_target_cell};
    end
    if (nargout > 2)
        varargout(3)= {Quat_dmp_Ft};
    end
end